### ISSUE TITLE
50.50 instead of 0.50

### ISSUE THREAD

**Issue by mcg88** [everettsouthwick/amazon-auto-reload#13]
As seen in the screenshot the app is typing in 50.50 instead of .50 in chrome. Interestingly, 51 cents seems to work as expected

![image](https://user-images.githubusercontent.com/4948638/58596486-4e065100-8242-11e9-993b-820d5c1426e1.png)

**Comment by ab763** [comment]
Thank you for reporting this. I’m guessing it doesn’t charge the incorrect amount for a couple of reasons, and is instead ‘only’ a visual bug, but my laptop is in to the shop for 5 days so I can’t address until then. I think one of the helping factors is some strong code that Everett originally put in which shouldn’t submit if the number Amazon has doesn’t match the number in your config. Offhand, I’d guess the cause is a couple of changes I made, including pre-loading the reload amount via a URL parameter but then the number is still typed out by the app as well. Regardless, I should fix it - and I have some other small code changes drafted anyway as well. Anyway, if you do have any concerns with the app I’d recommend to hold off using it until I have a chance to update once my laptop is back within 5 days. Thank you again for reporting.

**Comment by ab763** [comment]
Without PC access/brainstorming in my head how I’d solve this in code, I’m thinking that just before typing the amount I’d do a getText() on the existing WebElement, and only if the text isn’t already correct would I clear/type in the field.

**Comment by everettsouthwick** [comment]
I believe in the original version I cleared the reload amount input box every time because sometimes it would be autofilled and sometimes it wouldn't - so to be on the safe side it just always cleared it and re-entered it. I'm in the process of moving across the country so I don't know if I'll get an opportunity to take a look at it, but if ab763 hasn't fixed it by the time I'm relocated I'll take a stab at it.

**Comment by ab763** [comment]
Yeah, I looked at the code and figured it out and I'm working on the fix, thanks.

**Comment by ab763** [comment]
I committed a fix to my open public fork, and opened a pull request to @everettsouthwick's repo for him to approve.

In testing the issue prior to the fix, I did confirm that the code aborted after the incorrect value was entered, instead of submitting the reload with the incorrect value.

Description of the issue:
The reload amount was stored internally by the app as a number, so 0.50 was stored internally as 0.5. That stored value was then sent to Amazon as a URL parameter so that it was preloaded upon page load, but further code checked whether the number in Amazon matched what it truly should be, and typed the correct value if not - but didn't clear the incorrect value first. This resulted in an incorrect value being entered - but not submitted - as further code verified the value in the web interface a final time before submitting. In Amazon.reloadCard() we now pass the number to Amazon properly formatted as currency from the start. Although the code to type the value shouldn’t need to run, we again clear before typing just to be sure.

**Comment by ab763** [comment]
@mcgwebdesign: Everett merged the changes from https://github.com/ab763/finance-transact into his repo 6 days ago, if you want to test again.

**Comment by ab763** [comment]
No update from the OP since the original post, including after the reported fix 4 or 5 months ago, so I think we can close this, or @everettsouthwick if you'd like you could grant me access to close issues here.

**Comment by mcg88** [comment]
The fix worked. Thanks

**Comment by everettsouthwick** [comment]
@ab763 I sent you an invite to be added as a collaborator to this project.
